project_id = "mnziekrimlmvnrcwgmbk"

[functions.cleanup-nonces]
verify_jwt = false

[functions.cleanup-rate-limits]
verify_jwt = false

[functions.changenow]
verify_jwt = false

[functions.okx-dex]
verify_jwt = false

[functions.walletconnect-config]
verify_jwt = false

[functions.price-history]
verify_jwt = false

[functions.signed-orders]
verify_jwt = false

[functions.crypto-news]
verify_jwt = false

[functions.record-commission]
verify_jwt = false

[functions.register-referral]
verify_jwt = false

[functions.submit-claim]
verify_jwt = false

[functions.send-bridge-notification]
verify_jwt = false

[functions.execute-orders]
verify_jwt = false

[functions.xlama-api]
verify_jwt = false

[functions.zerion]
verify_jwt = false
