project_id = "mnziekrimlmvnrcwgmbk"

[functions.changenow]
verify_jwt = false

[functions.okx-dex]
verify_jwt = false

[functions.walletconnect-config]
verify_jwt = false

[functions.price-history]
verify_jwt = false

[functions.signed-orders]
verify_jwt = false

[functions.crypto-news]
verify_jwt = false

[functions.record-commission]
verify_jwt = false
